name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      # Automatic gradle caching using `actions/cache@v4`
      # https://github.com/gradle/actions/tree/main/setup-gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run test and lint
        run: ./gradlew lintKotlin testDebugUnitTest --parallel --daemon

      - name: Build with Gradle
        run: ./gradlew assembleDebug --parallel --daemon
