name: Android Release Build

# Workflow that builds release APK each time code changes.
# This allows developers and testers to easily download the latest release APK.
# This is also useful to download the APK and add to to the GitHub release.
#
# See:
# - https://github.com/usetrmnl/trmnl-android/tree/main/keystore
# - https://github.com/usetrmnl/trmnl-android/blob/main/app/build.gradle.kts#L44-L55


on:
  push:
    branches: [ "main" ]
  # This allows manual triggering of the workflow, which results in making Android Release APK build
  # Go to the "Actions" tab the repository, select this workflow, and click the "Run workflow" button to run it manually.
  workflow_dispatch: 

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Extract version name
        id: version
        run: |
          VERSION_NAME=$(grep -o 'versionName = "[^"]*"' app/build.gradle.kts | cut -d'"' -f2)
          echo "VERSION=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "App version name extracted: $VERSION_NAME"

      - name: Rename APK
        run: |
          mkdir -p artifact
          cp app/build/outputs/apk/release/app-release.apk artifact/trmnl-mirror-v${{ steps.version.outputs.VERSION }}.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: trmnl-mirror-app
          path: artifact/trmnl-mirror-v${{ steps.version.outputs.VERSION }}.apk
          # Use maximum allowed retention period
          # https://github.com/actions/upload-artifact?tab=readme-ov-file#retention-period
          retention-days: 90
