name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Java JDK versions (LTS: 17, 21 & Non-LTS: 23)
        java-version: [ '17', '21', '23' ]
        # https://adoptium.net/temurin/releases/
        distribution: [ 'temurin' ]

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}

      # Automatic gradle caching using `actions/cache@v4`
      # https://github.com/gradle/actions/tree/main/setup-gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run test
        run: ./gradlew testDebugUnitTest --parallel --daemon

      - name: Build with Gradle
        run: ./gradlew assembleDebug --parallel --daemon
