name: F-Droid Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # This allows manual triggering of the workflow, which results in making F-Droid APK build
  # Go to the "Actions" tab the repository, select this workflow, and click the "Run workflow" button to run it manually.
  workflow_dispatch: 

jobs:
  build-fdroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Build F-Droid APK
        run: ./gradlew buildFDroid

      - name: Extract version name
        id: version
        run: |
          VERSION_NAME=$(grep -o 'versionName = "[^"]*"' app/build.gradle.kts | cut -d'"' -f2)
          echo "VERSION=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "App version name extracted: $VERSION_NAME"

      - name: Rename APK
        run: |
          mkdir -p artifact
          cp app/build/outputs/apk/fdroid/release/app-fdroid-release-unsigned.apk artifact/trmnl-mirror-fdroid-v${{ steps.version.outputs.VERSION }}-unsigned.apk

      - name: Upload F-Droid APK
        uses: actions/upload-artifact@v4
        with:
          name: trmnl-mirror-fdroid-unsigned
          path: artifact/trmnl-mirror-fdroid-v${{ steps.version.outputs.VERSION }}-unsigned.apk
          # Use maximum allowed retention period
          # https://github.com/actions/upload-artifact?tab=readme-ov-file#retention-period
          retention-days: 90
