name: F-Droid Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # This allows manual triggering of the workflow, which results in making F-Droid APK build
  # Go to the "Actions" tab the repository, select this workflow, and click the "Run workflow" button to run it manually.
  workflow_dispatch: 

jobs:
  build-fdroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Run F-Droid Tests
        run: ./gradlew testFdroidDebugUnitTest
        
      - name: Decode Keystore
        if: "${{ env.KEYSTORE_BASE64 != '' }}"
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore
          echo "✓ Keystore decoded successfully"

      - name: Setup Signing Environment
        if: "${{ env.KEYSTORE_BASE64 != '' }}"
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "CI=true" >> $GITHUB_ENV
          echo "KEYSTORE_PATH=$GITHUB_WORKSPACE/release.keystore" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "✓ Signing environment variables set"
      
      - name: Build F-Droid APK
        run: ./gradlew assembleFdroidRelease

      - name: Extract version name
        id: version
        run: |
          VERSION_NAME=$(grep -o 'versionName = "[^"]*"' app/build.gradle.kts | cut -d'"' -f2)
          echo "VERSION=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "App version name extracted: $VERSION_NAME"

      - name: Rename APK
        run: |
          mkdir -p artifact
          cp app/build/outputs/apk/fdroid/release/app-fdroid-release.apk artifact/trmnl-mirror-fdroid-v${{ steps.version.outputs.VERSION }}.apk

      - name: Upload F-Droid APK
        uses: actions/upload-artifact@v4
        with:
          name: trmnl-mirror-fdroid
          path: artifact/trmnl-mirror-fdroid-v${{ steps.version.outputs.VERSION }}.apk
          # Use maximum allowed retention period
          # https://github.com/actions/upload-artifact?tab=readme-ov-file#retention-period
          retention-days: 90
